export const execCommands = [
  'backColor',
  'bold',
  'contentReadOnly',
  'copy',
  'createLink',
  'cut',
  'delete',
  'fontName',
  'fontSize',
  'foreColor',
  'formatBlock',
  'forwardDelete',
  'heading',
  'hiliteColor',
  'increaseFontSize',
  'indent',
  'insertBrOnReturn',
  'insertHorizontalRule',
  'insertHTML',
  'insertImage',
  'insertLineBreak',
  'insertOrderedList',
  'insertParagraph',
  'insertText',
  'insertUnorderedList',
  'italic',
  'justifyCenter',
  'justifyFull',
  'justifyLeft',
  'justifyRight',
  'outdent',
  'paste',
  'redo',
  'removeFormat',
  'selectAll',
  'strikethrough',
  'subscript',
  'superscript',
  'underline',
  'undo',
  'unlink',
  'useCSS',
  'styleWithCSS',
] as const;

export const TextEditorCommands = {
  basicFormatting: {
    bold: { title: 'Qalın', icon: 'Bold', command: 'bold' },
    italic: { title: 'İtalik', icon: 'Italic', command: 'italic' },
    underline: { title: 'Altı xətt', icon: 'Underline', command: 'underline' },
    strikethrough: { title: 'Üstü xətt', icon: 'Strikethrough', command: 'strikethrough' },
  },
  lists: {
    unorderedList: { title: 'Markerli Siyahı', icon: 'UnorderedList', command: 'insertUnorderedList' },
    orderedList: { title: 'Nömrələnmiş Siyahı', icon: 'OrderedList', command: 'insertOrderedList' },
  },
  links: {
    link: { title: 'Link Yarat', icon: 'Link', command: 'createLink' },
    unlink: { title: 'Linki Sil', icon: 'Unlink', command: 'unlink' },
  },
  alignment: {
    justifyCenter: { title: 'Mərkəzə', icon: 'JustifyCenter', command: 'justifyCenter' },
    justifyFull: { title: 'Eninə', icon: 'Justify', command: 'justifyFull' },
    justifyLeft: { title: 'Sola Doğru', icon: 'JustifyLeft', command: 'justifyLeft' },
    justifyRight: { title: 'Sağa Doğru', icon: 'JustifyRight', command: 'justifyRight' },
  },
  fontSize: {
    fontSize: { title: 'Şrift Ölçüsü', icon: 'FontSize', command: 'fontSize' },
  },
  removeFormat: {
    removeFormat: { title: 'Formatı Sil', icon: 'RemoveFormat', command: 'removeFormat' },
  },
  subscriptSuperscript: {
    subscript: { title: 'Aşağı İndeks', icon: 'Subscript', command: 'subscript' },
    superscript: { title: 'Yuxarı İndeks', icon: 'Superscript', command: 'superscript' },
  },
  horizontalRule: {
    horizontalRule: { title: 'Üfüqi Xətt', icon: 'HorizontalRule', command: 'insertHorizontalRule' },
  },
  textHighlight: {
    highlight: { title: 'İşarələ', icon: 'Highlight', command: 'hiliteColor', value: 'yellow' },
  },
};
