export const KeyCodes = {
  Space: " ",
  Backspace: "Backspace",
  Tab: "Tab",
  Enter: "Enter",
  Shift: "Shift",
  Control: "Control",
  Alt: "Alt",
  Pause: "Pause",
  CapsLock: "CapsLock",
  Escape: "Escape",
  PageUp: "PageUp",
  PageDown: "PageDown",
  End: "End",
  Home: "Home",
  ArrowLeft: "ArrowLeft",
  ArrowUp: "ArrowUp",
  ArrowRight: "ArrowRight",
  ArrowDown: "ArrowDown",
  Insert: "Insert",
  Delete: "Delete",
  Meta: "Meta",
  ContextMenu: "ContextMenu",
  NumLock: "NumLock",
  ScrollLock: "ScrollLock",
  Semicolon: "Semicolon",
  Equal: "Equal",
  Comma: "Comma",
  Dash: "Dash",
  Period: "Period",
  Slash: "Slash",
  Backquote: "Backquote",
  BracketLeft: "BracketLeft",
  Backslash: "Backslash",
  BracketRight: "BracketRight",
  Quote: "Quote",
};
